// Shared branded-CSV writer for CQIP exports. Plain text, no styling —
// same header + summary + footer shape as the XLSX counterpart so a
// leadership recipient downloading the CSV gets the same provenance
// line at the top and the same metric callouts.

export interface BrandedCsvOptions {
  title: string;
  subtitle?: string;
  summaryRows?: Array<{ label: string; value: string | number }>;
  headers: string[];
  rows: Array<(string | number | null)[]>;
  filename: string;
}

function escape(v: unknown): string {
  const s = v == null ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function downloadBrandedCsv(opts: BrandedCsvOptions): void {
  const lines: string[] = [];
  lines.push(escape(`CQIP — ${opts.title}`));
  if (opts.subtitle) lines.push(escape(opts.subtitle));
  lines.push('');

  if (opts.summaryRows && opts.summaryRows.length > 0) {
    for (const { label, value } of opts.summaryRows) {
      lines.push(`${escape(label)},${escape(value)}`);
    }
    lines.push('');
  }

  lines.push(opts.headers.map(escape).join(','));
  for (const row of opts.rows) {
    lines.push(row.map(escape).join(','));
  }

  lines.push('');
  const stamp = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
  lines.push(escape(`Generated by CQIP · ${stamp}`));

  const csv = lines.join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = opts.filename.endsWith('.csv') ? opts.filename : `${opts.filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
